25조 안드로이드 3주차 개
kakao-tech-campus-2nd-step3/Team25_Android pull request #16
Opened 2024-09-19 12:40 UTC by ichanguk

## 금주 개발 진행 상황
- 이용자 앱 UI 개발 완료
- 카카오 로그인 구현
- 도착지 병원 검색 기능 구현
- 출발지 주소 검색 기능 구현

## 차주 개발 예정 사항
- 매니저 등록 기능 구현
- 지도에 현재 위치 띄우는 기능 구현
- 결제 기능 구현
- 예약 정보 확인 기능 구현

## 완성된 UI들

![KakaoTalk_20240919_213724746](https://github.com/user-attachments/assets/b075d1a2-ade4-4e6b-bb37-3dcfebc32e96)
![KakaoTalk_20240919_213724746_01](https://github.com/user-attachments/assets/70efc8fa-7071-4e26-9ea6-4c5e8309d2ab)
![KakaoTalk_20240919_213724746_02](https://github.com/user-attachments/assets/ee2f594c-48e5-4f7f-adc5-fa2cb03c52a0)
![KakaoTalk_20240919_213724746_03](https://github.com/user-attachments/assets/31f4e24b-8f5e-46b2-9948-e716de387474)
![KakaoTalk_20240919_213724746_04](https://github.com/user-attachments/assets/edb89268-3877-420d-a831-491ade1f5c06)
![KakaoTalk_20240919_213724746_05](https://github.com/user-attachments/assets/bf0f655f-e1bc-4f65-8ba1-1835a88ae6ac)
![KakaoTalk_20240919_213724746_06](https://github.com/user-attachments/assets/573e06e5-3c1c-472d-8d91-316240605515)
![KakaoTalk_20240919_213724746_07](https://github.com/user-attachments/assets/62d16541-0911-4065-b6b3-0634449914d8)
![KakaoTalk_20240919_213724746_08](https://github.com/user-attachments/assets/c6dfdfce-3ba0-4020-bb8a-23cb1b2aabf0)
![KakaoTalk_20240919_213724746_09](https://github.com/user-attachments/assets/b365ef32-410e-4cb6-8139-cd2ce066f97c)
![KakaoTalk_20240919_213724746_10](https://github.com/user-attachments/assets/ea69123d-0fc0-4b2c-add3-f623fc38d8c8)
![KakaoTalk_20240919_213724746_11](https://github.com/user-attachments/assets/5bf5a765-3897-44bb-a06e-388d3abad19b)
![KakaoTalk_20240919_213724746_12](https://github.com/user-attachments/assets/3786fb5e-43bf-43c9-9e7e-7b123d6cfe0c)
![KakaoTalk_20240919_213724746_13](https://github.com/user-attachments/assets/57ce5fd9-e991-4b5f-b5a8-ef41b8a191a4)

2024-09-24 02:28 UTC, bigstark commented
안녕하세요 25조 여러분! 반갑습니다 :) 이번 step3 리뷰를 맡게된 강대규라고 합니다. 잘부탁드려요. 

PR 을 남길 때 아래와 같은 사항들이 고려되었으면 좋겠어요.

## PR 사이즈를 최소화하자.
- PR 의 사이즈가 크면 리뷰가 어려워지며, 리뷰의 맥락을 파악하기 어려워지는 단점이 존재해요. 
- PR 의 사이즈가 크다 함은 보통 files changed 가 10~15 가 넘어가는 순간들입니다. 
- 물론 PR 의 성격에 따라 다르겠지만, 최대한 잘게 쪼갠 PR 이 리뷰하기 좋습니다.
- 또한 여러분들이 작업의 단위를 나누기에도 좋을거에요. 

## 하나의 PR 은 하나의 이슈만 담자.
- 위와 같은 맥락으로 하나의 PR 에 여러 개의 이슈를 담아내게 된다면 코드의 변경이 어떤 이슈로 인해 변경이 된 것인지 파악하기 힘들어져요.
- 작업의 단위를 이슈로 만들어주셨는데, 하나의 이슈당 하나의 PR 을 만드는 것이 조금 더 좋아보여요.
- 만약 그것이 1 file changed, 1 commit 이라고 하더라도 말이죠 👍 

하나의 PR 을 성의없이 리뷰하는 것보다 N 개의 PR 을 빠르고 꼼꼼히 리뷰하는 것이 좋을 것 같아요 :)
여러분 이번 과정도 파이팅입니다!

2024-09-24 04:39 UTC, bigstark requested changes
XML 은 따로 리뷰하지는 않았어요. 전반적으로 정렬이 한번씩 필요한 것 같고, xml 의 id 의 네이밍 규칙을 정하면 좋을 것 같습니다. 

굉장히 많은 것을 해주셨지만, 너무 많은 정보가 담겨있는 PR 은 제대로 리뷰를 할 수가 없는 상태에요! 번거롭더라도 자주자주 PR 을 요청해주시면 작게 자주 보는 형식으로 진행해볼게요!

2024-09-24 04:39 UTC, bigstark commented on .editorconfig
> +disabled_rules = import-ordering,comment-spacing, Unexpected indentation
현업 경험 있으신분 있나요?!

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/MyApplication.kt
> +    }
너무 잘 작성해주셨는데요, 이런것들도 HospitalInitializer 와 같은 클래스로 따로 분리하고, 해당 App 내에서는 initialize 메소드 하나만 호출하게 하여, 관리의 용이성을 챙기면 더 좋을 것 같습니다!

```kotlin
class HospitalInitializer @Inject constructor(val hospitalDao: HospitalDao) {
    ..
    fun initialize(coroutineScope: CoroutineScope) {
        ..
    }
}
```
와 같은 형식으로요

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/di/DatabaseModule.kt
> +    }
singleton 으로 제공될 필요는 없을까요?

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/di/NetworkModule.kt
> +    }
이것도 마찬가지로 singleton 으로 제공할 필요는 없을까요?

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/di/ServiceModule.kt
> +        val isRemoteMode = false
remote mode 에 따라 제공이 되어야 한다면, remote mode 도 주입받을 수 있도록 해야하지 않을까요?

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/domain/HospitalDomain.kt
> +):Parcelable
하나의 클래스가 parcelable 이기도 하고, entity 이기도 하면서 dto 임과 동시에 domain 이네요. 분리해주셔야할 것 같습니다.

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/login/LoginViewModel.kt
> +        _socialLoginUiState.tryEmit(SocialLoginUiState.SocialLoginUiSuccess)
tryEmit 은 되도록이면 사용하지 않는것이 좋아요. state flow 라면 update 를 적극적으로 사용하심이 좋을 것 같습니다.

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/login/LoginEntryActivity.kt
> +class LoginEntryActivity : AppCompatActivity() {
`@AndroidEntryPoint` 추가는 필요 없을까요? 추후 이 화면은 hilt 종속성은 계획에 없나요

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/login/SocialLoginUiState.kt
> +    object SocialLoginUiSuccess : SocialLoginUiState
음... 성공했다는 ui state 는 조금 어색한 것 같긴해요. UiState 에 대한 얘기는 다음 멘토링때 자세히 얘기해보는 것으로 해보죠.

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/main/companion/adapters/LiveCompanionRecyclerViewAdapter.kt
> +    inner class LiveCompanionViewHolder(val binding: ItemLiveCompanionStatusBinding) :
VIewHolder 에 inner class 를 사용하는 것은 최대한 지양해주세요!

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/main/status/ReservationCancelActivity.kt
> +        val reservationInfo: ReservationInfo? = intent.getParcelableExtra("ReservationInfo")
ReservationInfo 과 같은 key 값은 하나로 관리되는 것이 좋습니다.
```kotlin
class ReservationCancelActivity : AppCompatActivity() {
    ....
    companion object {
        const val KEY_RESERVATION_INFO = "ReservationInfo"
    }
}
```

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/main/status/ReservationCheckReportActivity.kt
> +}
이런 로직이 activity 에 있는 것이 어색합니다. ViewModel 로 이동해주시면 좋을 것 같아요.

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/main/status/adapters/ReservationHistoryRecyclerViewAdapter.kt
> +            }
Adapter 에서 startActivity 를 직접적으로 호출하는 것은 안티팬턴입니다. callback 을 통해서 Activity 에서 실행해주시면 좋을 것 같습니다.

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/main/status/adapters/ReservationStatusRecyclerViewAdapter.kt
> +                binding.root.context.startActivity(intent)
여기도 마찬가지!

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/main/status/adapters/ReservationHistoryRecyclerViewAdapter.kt
> +        }
items 는 same 이나 contents 가 same 이 아닌 경우도 발생할 수 있을 것 같아요. contents the same 에서는 id 도 같이 비교해주는게 좋을 것 같습니다.

2024-09-24 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/reservation/ReservationStep9Activity.kt
> +class ReservationStep9Activity : AppCompatActivity() {
ReservationStep 각각을 ACtivity 로 작성한 이유가 잇을까요? step 이 11개나 되는데요...!

2024-09-26 13:03 UTC, ichanguk commented on app/src/main/java/com/example/team25/ui/reservation/ReservationStep9Activity.kt
> +class ReservationStep9Activity : AppCompatActivity() {
fragment + viewmodel을 사용하는 형태로 수정하겠습니다

2024-09-27 19:48 UTC, bigstark commented on app/src/main/java/com/example/team25/di/NetworkModule.kt
> +    }
이부분은 추후 적용 부탁드려요!

2024-09-27 19:48 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/login/SocialLoginUiState.kt
> +    object SocialLoginUiSuccess : SocialLoginUiState
이부분도 추후 변경 부탁드려요!

2024-09-27 19:49 UTC, bigstark approved these changes

2024-09-27 19:49 UTC, merged