안드로이드 25조 5주차 개발 완료(이용자 앱)
kakao-tech-campus-2nd-step3/Team25_Android pull request #46
Opened 2024-10-04 12:48 UTC by ichanguk

## 금주 개발 사항

- 결제 기능 구현(https://github.com/kakao-tech-campus-2nd-step3/Team25_Android/pull/24)
- 예약 정보 viewmodel에 저장하도록 구현
(https://github.com/kakao-tech-campus-2nd-step3/Team25_Android/pull/32, https://github.com/kakao-tech-campus-2nd-step3/Team25_Android/pull/33, )
- 병원 정보 클릭 리스너 매개변수 추가(https://github.com/kakao-tech-campus-2nd-step3/Team25_Android/pull/39)
- 폴더 구조 정리(https://github.com/kakao-tech-campus-2nd-step3/Team25_Android/pull/40)
- 로그인 구현(https://github.com/kakao-tech-campus-2nd-step3/Team25_Android/pull/42)

## 차주 개발 예정 사항

- 서버와 api 연동(로그인, 매니저 등록, 매니저 검색, 예약, 결제)

2024-10-06 15:11 UTC, bigstark reviewed
이번주도 고생 많으셨습니다! 코멘트 확인 부탁드려요 👍 

그나저나 정렬상태가 굉장히 이상해진 것 같은데, 이부분도 확인해주시면 좋을 것 같네요!

2024-10-06 15:11 UTC, bigstark commented on app/src/main/java/com/example/team25/data/Utils.kt
> +    ) {
오잉 indent 가 조금 이상한데요! ㅎㅎ

2024-10-06 15:11 UTC, bigstark commented on app/src/main/java/com/example/team25/data/Utils.kt
> +            }
p4; Utils 가 hilt 로 제공될 목적이라면 해당 메소드는 제거해도 좋을 것 같네요.

2024-10-06 15:11 UTC, bigstark commented on app/src/main/java/com/example/team25/data/Utils.kt
> +            private var prefsEditor: SharedPreferences.Editor? = null
p5; SharedPreference 의 사용보다는 [DataStore](https://developer.android.com/topic/libraries/architecture/datastore) 를 사용해보는건 어때요?

2024-10-06 15:11 UTC, bigstark commented on app/src/main/java/com/example/team25/data/network/dto/TokenDto.kt
> +)
p3; expiresIn 과 같은 데이터는 따로 없어도 괜찮을까요?

2024-10-06 15:11 UTC, bigstark commented on app/src/main/java/com/example/team25/data/network/dto/TokenDto.kt
> +)
p3;  DTO 라면 SerializedName 을 항상 붙여주는게 어떨까요?

2024-10-06 15:11 UTC, bigstark commented on app/src/main/java/com/example/team25/di/LoginModule.kt
> +@InstallIn(SingletonComponent::class)
p4; LoginRepository 의 사용이 공유될 필요가 없다면 ViewModelComponent 에 있어도 괜찮을 것 같네요!

2024-10-06 15:11 UTC, bigstark commented on app/src/main/java/com/example/team25/di/NetworkModule.kt
> +        val url = "https://ollagaljido.net/"
p3; base url 은 gradle.properties 등에서 관리하는 것이 어떨까요!

2024-10-06 15:11 UTC, bigstark commented on app/src/main/java/com/example/team25/di/NetworkModule.kt
>      @Provides
p3; KakaoRetrofit 도 qualifer 로 구분해주셨으니, 일반적인 retrofit 도 qualifer 로 구분해주시면 좋을 것 같네요!

2024-10-06 15:11 UTC, bigstark commented on app/src/main/java/com/example/team25/domain/usecase/LoginUseCase.kt
> +        suspend operator fun invoke(accountLoginDto: AccountLoginDto): TokenDto? {
p4; usecase 에서는 dto 를 모르게 하는게 어때요? oauthAccessToken 만 받아도 괜찮을 것 같아요.

2024-10-06 15:11 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/login/LoginEntryActivity.kt
> +        intent.putExtra("userNickname", nickname)
p4; userNickname 과 같은 Key 값은 사용하는 곳에서 companion object 에 정리해두면 더욱 더 좋을 것 같아요!

2024-10-06 15:11 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/login/LoginState.kt
> +    data class Success(val token: TokenDto) : LoginState()
p3; ui state 에서 token dto 를 사용할 일이 있나요?

2024-10-06 15:13 UTC, bigstark requested changes

2024-10-06 15:13 UTC, bigstark commented on app/src/main/java/com/example/team25/di/NetworkModule.kt
> +    fun provideRetrofit(): Retrofit {
p2; 추가적으로 retrofit 은 `@Singleton` 으로 나가야할 것 같네요!

2024-10-07 08:30 UTC, ichanguk commented on app/src/main/java/com/example/team25/data/network/dto/TokenDto.kt
> +)
백엔드와 얘기되는 대로 추가하겠습니다.

2024-10-07 14:54 UTC, ichanguk commented on app/src/main/java/com/example/team25/ui/login/LoginEntryActivity.kt
> +        intent.putExtra("userNickname", nickname)
이 부분 빠뜨렸는데 다음 pr에 수정해서 추가하겠습니다

2024-10-08 02:13 UTC, bigstark commented on app/src/main/java/com/example/team25/di/NetworkModule.kt
> +    fun provideRetrofit(): Retrofit {
@ichanguk 이부분만 추가해주시면 머지해보도록 해볼게요

2024-10-08 03:36 UTC, ichanguk commented on app/src/main/java/com/example/team25/di/NetworkModule.kt
> +    fun provideRetrofit(): Retrofit {
@bigstark 추가 완료했습니다. 이제 review 브랜치로 바로바로 pr 올리도록 하겠습니다.

2024-10-08 03:51 UTC, ichanguk commented on app/src/main/java/com/example/team25/di/NetworkModule.kt
> +    fun provideRetrofit(): Retrofit {
![image](https://github.com/user-attachments/assets/5fc9cd4d-7d86-4d43-8815-c06f3cb4c673)
기존의 위와 같은 방식에서
![image](https://github.com/user-attachments/assets/9c5e2fd7-a049-495b-bde4-319fac301120)
이와 같은 방식으로 변경한다고 이해하면 될까요?

2024-10-08 04:39 UTC, bigstark commented on app/src/main/java/com/example/team25/di/NetworkModule.kt
> +    fun provideRetrofit(): Retrofit {
넵넵 이렇게 그렇게 진행해주시면 좋을 것 같아요!

2024-10-08 04:40 UTC, bigstark approved these changes
수고하셨어요 :)

2024-10-08 04:40 UTC, merged